version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: fullstack-project-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: fullstack_project_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - fullstack-network

volumes:
  mysql-data:

networks:
  fullstack-network:
    driver: bridge