server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8061/eureka/

spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "http://127.0.0.1:5500"
            allowedHeaders:
              - "Origin"
              - "Content-Type"
              - "Accept"
              - "Authorization"
              - "Referer"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowCredentials: true
      routes:
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/api/posts/**
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/api/comments/**
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/api/auth/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/api/reviews/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_FIRST

logging:
  level:
    org.springframework.cloud.gateway: DEBUG